# Generated by Django 4.2.2 on 2024-10-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="s_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
    ]
