# Generated by Django 5.1 on 2024-10-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_count_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Просмотры"
            ),
        ),
    ]
