# Generated by Django 5.1 on 2024-10-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
